# (PART) Version en Français {-}

# Code de conduite {#codedeconduite}

La **série d’ateliers et le symposium R du CSBQ** ont l’objectif de fournir un environnement accueillant et favorable à toutes les personnes, indépendamment de leur origine ou de leur identité.

Toute personne qui participe, présente, développe, ou organise un atelier R du CSBQ et d'autres activités connexes **accepte** le présent code de conduite lorsqu'elle est présente à une activité liée à un atelier.

Nous ne tolérons pas les comportements irrespectueux, intimidants ou gênants pour les autres.

Nous ne tolérons pas la discrimination contre (y compris, sans toutefois s'y limiter) l'orientation sexuelle, le handicap, l'apparence physique, la citoyenneté, l'origine ethnique, la situation familiale, la religion ou les croyances (ou l’absence), l'appartenance à une minorité, l'âge, l'éducation et la situation socio-économique.

Ce code s'applique à tous les espaces gérés par l'atelier ou affiliés à l'atelier, y compris, sans toutefois s'y limiter, les ateliers, les listes de diffusion et les forums en ligne tels que GitHub, Slack et Twitter.

Les personnes qui participent aux ateliers qui enfreignent ces règles peuvent être sanctionnées ou expulsées, sans remboursement, à notre discrétion.

#### Comportement prévisible {-}

Toutes les personnes qui participent ou présentent un atelier doivent faire preuve de respect et de courtoisie envers les autres. Toutes les interactions doivent être professionnelles, quelle que soit la plate-forme: en ligne ou en personne. Afin de créer un environnement d'apprentissage positif et professionnel, nous encourageons les comportements suivants dans tous les ateliers et plateformes:

* Utiliser un langage accueillant et inclusif;
* Soyez respectueux des différents points de vue et expériences;
* Accepter gracieusement les critiques constructives;
* Concentrez-vous sur ce qui convient le mieux à la communauté;
* Faites preuve de courtoisie et de respect envers les autres membres de la communauté.


#### Comportement inacceptable {-}

Les exemples de comportement inacceptable des personnes qui présentes à tout événement / plate-forme d'atelier incluent:

* les commentaires écrits ou verbaux qui ont pour effet d'exclure des personnes en raison de leur appartenance à un groupe spécifique;
* amener une personne à craindre pour sa sécurité, par exemple par le harcèlement criminel ou l'intimidation;
* menaces violentes ou langage dirigé contre une autre personne;
* l'affichage d'images sexuelles ou violentes;
* attention sexuelle importune;
* contact physique non consensuel ou importun;
* insultes ou rabaissements;
* blagues sexistes, racistes, homophobes, transphobes, capacitables ou exclusives;
* incitation à la violence, au suicide ou à l'automutilation;
* continuer à initier une interaction (y compris des photographies ou des enregistrements) avec quelqu'un après avoir été invité à s'arrêter;
* publication de communication privée sans consentement.

Si une personne qui participe à l'atelier adopte un comportement harcelant, nous pouvons prendre toutes les mesures que nous jugeons appropriées, y compris avertir cette personne ou l’expulser de l'atelier sans remboursement. Les personnes à qui il est demandé de mettre fin à tout comportement de harcèlement doivent se conformer immédiatement.

En cas d'harcèlement, ou pour toute autre question, veuillez contacter immédiatement l'équipe de présentation de l'atelier, ainsi que l'équipe de coordination de la série d'ateliers R du CSBQ.
