# Préparation {#preparation-fr}

Être un présentateur ou une présentatrice de la série d'ateliers R du CSBQ demande une préparation et une communication proactive avec les participants inscrits aux ateliers.

Ci-dessous, il y a une liste de points qui vous aideront à préparer les ateliers. Nous vous demandons de les lire **attentivement**.

## Avant l'atelier

### Deux semaines avant l'atelier

1. Obtenez la liste des participants et participantes inscrits à votre atelier (nous vous fournirons un script pour faire ceci). Ensuite, déterminez le nombre de présentateurs et de présentatrices (et/ou d'assistants et d'assistantes) qui peuvent être attribués à votre atelier:

> NOUVEAU: **En septembre 2021, le prix d'apprentissage et de développement pour les présentateurs de la série d'ateliers R a augmenté de 125 $ à 150 $.** Il y a également de nouvelles distinctions dans le processus de paiement du prix entre les membres CSBQ de McGill et les membres CSBQ non-McGill, y compris une **compensation fiscale supplémentaire pour les membres non-McGill**. Voir la section [Paiement](#payment-fr) pour plus d'informations.

Nombre de participants | Nombre de présentateurs | Paiement par présentateur | Allocation de fonds à l'atelier
:-------------: | :-------------: | :-------------: | :-------------:
1 to 5 | 1 | $150 | $150
6 to 14 | 2 | $150 | $300
15 or more | 3 | $150 | $450

* **Pour les ateliers à distance:** Nous avons besoin *d'au moins* deux présentateurs ou présentatrices par atelier pendant les ateliers à distance. Pendant qu'un instructeur ou qu'une instructrice présente l'atelier, l'autre présentateur ou présentatrice doit agir en tant qu'assistant.e, en surveillant la conversation, en gérant des salles de sous-commission (en anglais, *breakout rooms*) et en aidant à déboguer les éventuels problèmes que les participants peuvent rencontrer. Les instructeurs, instructrices, assistants, et assistantes des ateliers doivent répondre aux questions des étudiants.

> *Si le nombre de présentateurs et présentatrices inscrits est inférieur au nombre de présentateurs et présentatrices pouvant être alloués à votre atelier, n'hésitez pas à inviter d'autres étudiants et étudiantes du deuxième et troisième cycles supérieurs et des post-doctorants ou post-doctorantes qui sont membres du CSBQ et qui, selon vous, pourraient vous aider avec l'instruction et l'assistance de l'atelier!*

> Notez que le **prix maximum** pour l'instruction ou l'assistance des ateliers R du CSBQ est de 150 $ par personne, par atelier.*

2. Familiarisez-vous avec le matériel disponible dans le [wiki](https://wiki.qcbs.ca/r) et la [présentation](https://qcbsrworkshops.github.io/) pour votre atelier.

  * **Assurez-vous d'être *très* à l'aise avec le contenu et la présentation de l'atelier à la date de votre présentation.**

  * Il est de **votre responsabilité** de vous familiariser avec le matériel.

  * Utilisez les [pages wiki](https://wiki.qcbs.ca/r) et les [présentations](https://qcbsrworkshops.github.io/) comme matériel de référence pour votre atelier. N'hésitez pas à compléter vos connaissances avec d'autres références et matériels.

  * Les présentations sont dotées d'un *mode présentateur*, qui permet la demonstration des notes et de donner un atelier plus dynamique. Consultez notre section "[Mode présentateur](#mode-presentateur)" pour en savoir plus.

3. Lisez le code de conduite (Section \@ref(codedeconduite)).

4. **Pour les ateliers à distance**: Familiarisez-vous avec Zoom avant votre atelier. Par exemple, vous devriez savoir: (i) comment partager votre écran; (ii) comment ouvrir et fermer les salles de conférence ("Breakout Rooms"); (iii) comment préparer et lancer des sondages; (iv) et [quels sont les outils disponibles pour interagir avec les étudiants](https://zoom.us/docs/doc/Tips%20and%20Tricks%20for%20Teachers%20Educating%20on%20Zoom.pdf). Nous avons fourni des conseils détaillées complémentaires pour ces tâches [ici](#conseils-zoom).

### Une semaine avant l'atelier

1. Obtenez la liste à jour des participants inscrits à votre atelier en utilisant le code qui vous a été envoyé lors de votre recrutement.

* *NOTE:* Souvenez-vous que pour les ateliers en ligne, vous devez utiliser l'option `"En_ligne"` pour l'argument `location`.

2. Envoyez le *message standardisé* ci-dessous à tous les participants, en remplaçant les champs si nécessaire.

> Idéalement, les instructeurs dont les courriels sont affichés dans le [calendrier de l'atelier](https://wiki.qcbs.ca/r#horaire_schedule) seront les premiers à communiquer avec les participants. Vous pouvez changer ce rôle, si vous le préférez.

* *NOTE:* Copiez au carbone (en « Cc ») toutes vos communications aux autres instructeurs et instructrices de votre atelier.
* *NOTE:* Ajoutez toutes les participants comme destinataires en copie carbone invisible (c.à.d., « Cci » ou « Bcc »).
* *NOTE:* Vous devez envoyer le message ci-dessous **au moins** 7 jours avant la date de votre présentation.
* *NOTE:* Vous **ne pouvez pas** supprimer des informations du texte suivant.


**Pour les ateliers de formation à distance** :

> Sujet du message : [Série d'ateliers R du CSBQ] Atelier #**X** - **Nom de l'atelier** (vendredi, **jour du mois**)

> Bonjour !
>
> Vous êtes inscrit à l'atelier R du CSBQ #**XXX** qui aura lieu le **JOUR DE LA SEMAINE** à **HH:MM** **PM ou AM**. En préparation de l'atelier, veuillez noter ce qui suit :
>
> 1) L'atelier sera donné par l'intermédiaire de Zoom. Une fois votre inscription terminée, vous devriez avoir reçu une invitation contenant un lien unique. Vous ne devez pas partager ce lien avec d'autres personnes.
>
> 2) Veuillez préparer votre ordinateur portable et les programmes correspondants (R et RStudio) au préalable. Vous pouvez également télécharger le script que nous utiliserons dans cet atelier sur le site web suivant : **https://wiki.qcbs.ca/r_workshopXX**
>
> 3) Nous vous recommandons d'exécuter l'intégralité du script au moins une fois avant la session de l'atelier afin de vous assurer que tout fonctionne sur votre ordinateur portable. En outre, nous vous recommandons de télécharger et d'installer toutes les bibliothèques que nous utiliserons pendant l'atelier.
>
> 4) Si vous ne pouvez plus vous rendre à l'atelier, veuillez nous en informer 5 jours à l'avance par e-mail. Notez que la préparation de cet atelier dépend du nombre de participants. Le fait de ne pas nous informer de votre absence entraînera une pénalité de 100$ facturée à votre directeur ou directrice de recherche.
>
> 5) Si vous n'êtes pas membre du CSBQ, il peut vous être demandé de nous envoyer un reçu de paiement pour participar dans l'atelier.
>
> 6) Notez que beaucoup d'efforts ont été déployés dans la planification de ces ateliers. Il est important que vous restiez engagé dans l'apprentissage et, si nécessaire, que vous participiez activement aux discussions et collaboriez avec vos pairs.
>
> 7) Nous vous encourageons à laisser votre caméra allumée pour permettre les instructeurs et instructrices de se connecter avec vous.
>
> 8) Si vous avez des questions concernant cet atelier, veuillez contacter l'un des présentateurs ou présentatrices afin que nous puissions vous aider !
>
> Nous avons hâte de vous voir le **JOUR DE LA SEMAINE** !
>
> **VOTRE(VOS) NOM(S)**


**Pour les ateliers en personne** :

> Sujet du message : [Série d'ateliers R du CSBQ] Atelier #**X** - **Nom de l'atelier** (vendredi, **jour du mois**)

> Bonjour !
>
> Vous êtes inscrit à l'atelier R du CSBQ #**XXX** qui sera donné à **NOM DE L'UNIVERSITÉ** ce prochain **JOUR DE SEMAINE** à **H:MM** **PM ou AM**. En préparation de cet atelier, veuillez noter ce qui suit :
>
> 1) L'atelier sera donné dans le bâtiment **XXX**, salle **XXX**.
>
> 2) Veuillez venir avec votre ordinateur portable et les programmes correspondants (R et RStudio) installés. Vous pouvez également télécharger le script que nous utiliserons dans cet atelier sur le site web suivant : **https://wiki.qcbs.ca/r_workshopXX**.
>
> 3) Nous vous recommandons d'exécuter le script complet au moins une fois avant de venir à l'atelier pour vous assurer que tout fonctionne sur votre ordinateur portable et pour télécharger et installer toutes les bibliothèques que nous utiliserons pendant l'atelier.
>
> 4) Si vous ne pouvez plus vous rendre à l'atelier, veuillez nous en informer 5 jours à l'avance par courriel, sinon, vous recevrez une pénalité de 100$ qui sera facturée à votre directeur ou directrice de recherche.
>
> 5) Si vous n'êtes pas membre du CSBQ, veuillez apporter le reçu du paiement à l'atelier.
>
> 6) L'accès à l'internet ne devrait pas être nécessaire pour suivre l'atelier si vous avez exécuté le script avant de venir pour vous assurer que vous aviez téléchargé toutes les bibliothèques nécessaires. Si vous suivez l'atelier dans une autre institution que la vôtre et que vous souhaitez avoir accès à l'internet pendant l'atelier, veuillez vous assurer que vous pouvez vous connecter au réseau *eduroam* (plus d'informations ici : http://qcbs.ca/wiki/eduroam). Si vous n'avez pas accès à eduroam ou au réseau de l'université, il se peut que nous ne puissions pas vous fournir un accès temporaire à l'internet.
>
> 7) Si vous avez des questions concernant cet atelier ou son lieu, veuillez contacter l'un des présentateurs afin que nous puissions vous aider au mieux !
>
> Merci, et nous avons hâte de vous voir !
>
> **VOTRE(VOS) NOM(S)**.


## Le jour de l'atelier

**Nous avons élaboré une [session dédiée avec des lignes directrices](#presentation-fr) sur ce que les instructeurs, les instructrices, les assistants et les assistantes doivent faire pendant l'atelier.**

**S'il vous plaît, [lisez et appliquez-les](#presentation-fr) très attentivement !**

## Après l'atelier

> Nous vous demandons de bien vouloir suivre les étapes ci-dessous *immédiatement* après votre présentation.

1. Envoyez le formulaire de retour d'information aux participants de votre atelier :

> Sujet du message : [Série d'ateliers R du CSBQ] Formulaire d'évaluation pour l'atelier #**X** - **Nom de l'atelier**

> Bonjour à nouveau !
>
> Merci d'être venus à l'atelier (#X) sur **Nom de l'atelier**.
>
> Nous vous demandons de bien vouloir prendre quelques minutes pour nous faire part de vos commentaires (https://docs.google.com/forms/d/12LiuK1hhCpuDULBYStlXoJi6K1sKTVeGzPiD5DVGdds/edit?urp=gmail_link) sur l'atelier auquel vous venez de participer.
>
> Ce processus est très précieux pour nous car nous pouvons comprendre où l'atelier a besoin d'être amélioré.
>
> Vos commentaires et suggestions sont très appréciés et sont lus avec attention.
>
> Merci encore !
>
> Avec nos sincères salutations,
> **VOTRE(VOS) NOM(S)**

2. [Donnez votre avis](https://goo.gl/forms/85TXCiQ9tW9nvq922) sur l'atelier que vous venez de présenter.

3. Envoyez le message ci-dessous aux participants et participantes inscrits qui ne se sont pas présentés (c'est-à-dire les participants qui ne vous ont pas envoyé de message annulant leur inscription et qui étaient absents pendant votre atelier).

* **NOTE** : Envoyez des messages **séparés** à chacune des absences enregistrées (c'est-à-dire n'incluez *pas* d'autres participants dans vos communications).

> Sujet du message : [Série d'ateliers du CSBQ R] Absence pendant l'atelier #**X** - **Nom de l'atelier**

> Cher **NOM DU PARTICIPANT INSCRIT**,
>
> Je vous contacte parce que vous étiez absent de l'atelier d'aujourd'hui (**XX**) sur **Nom de l'atelier**, qui a été donné **en lieu ou à distance**.
>
> Selon la politique de la Série d'ateliers R du CSBQ, les participant.e.s inscrit.e.s qui n'annulent pas leur participation *au moins* 5 jours à l'avance par courriel encourent une pénalité de 100$ qui est facturée au compte institutionnel de leur superviseur.
>
> Nous vous prions de bien vouloir nous contacter au sujet de votre absence dans les meilleurs délais.
>
> Avec nos salutations,
> **VOTRE(VOS) NOM(S)**
