# Présentation {#presenter-fr}

Les recommandations suivantes ont été rédigées afin d'améliorer le contenu des ateliers pour les participants. Nous proposons des lignes directrices basées sur des stratégies d'enseignement et d'apprentissage factuelles. Même si certains aspects peuvent vous sembler évidents, nous vous demandons de les lire *avec attention*.

## Structure de l'atelier

En moyenne, les ateliers en personne durent 4 heures (pauses incluses), avec une certaine variabilité en fonction du contenu et de la complexité de l'atelier.

* Les ateliers à distance devraient durer environ 3 heures. Les ateliers sont raccourcis pour s'adapter à ce nouveau format. En général, nous proposons que le temps d'instruction soit divisé en deux sections d'une heure et demie, avec une pause d'une heure entre les deux. Toutefois, certains ateliers peuvent bénéficier d'un déroulement différent, *par exemple* deux pauses de 30 minutes au lieu d'une longue pause d'une heure. *Les suggestions pour les ateliers 1 à 5 sont fournies ci-dessous.*

Chaque atelier doit commencer par une période d'accueil et d'enregistrement d'environ 5 minutes. Pendant cette période, les présentateurs et les assistants des ateliers peuvent prendre la parole, demander aux participants comment ils se sentent, et leur donner des instructions sur la façon d'utiliser le "chat" et de poser des questions.

Après la période de bienvenue et d'enregistrement, les présentateurs doivent commencer l'instruction de l'atelier en illustrant et en précisant le contenu et la structure de l'instruction et des pauses.

> Lors des ateliers à distance et en personne, de courtes pauses supplémentaires de 5 à 10 minutes (chacune) devraient être prévues à l'occasion pour permettre aux participants et aux présentateurs de faire une courte pause et de répondre aux questions en suspens.

À la fin de l'atelier, les présentateurs et les assistants doivent remercier les participants pour leur présence, leur demander de remplir le questionnaire de retour d'information et leur permettre de poser des questions (si le temps le permet).

Suggestions de structures pour les ateliers 1 à 5 :

|     Blocks    |  Atelier 1    | Atelier 2 |  Atelier 3 | Atelier 4 | Atelier 5 |
| -------------:|:-------------:| ----------:|:-------------:| ----------:| ----------:|
| Bienvenue et enregistrement | 5 minutes   |    5 minutes       | 5 minutes  | 5 minutes | 5 minutes |
| Instruction | 85 minutes   |    85 minutes       | 85 minutes       |    85 minutes      | 55 minutes  |
| Pause  | 60 minutes      |    60 minutes      |60 minutes      |    60 minutes      | 30 minutes |
| Instruction | 85 minutes   |    85 minutes       | 85 minutes       |    85 minutes      | 85 minutes  |
| Pause  | *Non applic.* |    *Non applic.*      | *Non applic.*  |    *Non applic.*  | 30 minutes |
| Instruction | *Non applic.*   |    *Non applic.*       | *Non applic.*  | *Non applic.* | 55 minutes  |
| Conclusion | 5 minutes   |    5 minutes       | 5 minutes  | 5 minutes | 5 minutes  |

## Directives générales

La journée de l'atelier, les instructeurs et les assistants doivent:

1. Arriver *au moins* 15 minutes avant le début de votre atelier pour préparer la salle de présentation et projeter votre présentation. 

* Pour les ateliers à distance, ouvrez la salle Zoom tôt (en même temps que la présentation, le wiki et le RStudio) et enregistrez-vous auprès de votre co-présentateur avant l'arrivée des participants ;

2. Prenez les présences ;

3. Recueillez les reçus des non-membres ;

4. Commencez votre présentation **ponctuellement**.

## Directives pour la présentation

1. Les instructeurs devraient se considérer comme des étudiants pendant le processus d'apprentissage, et être attentifs à leur méthode d'enseignement et de communication, ainsi qu'à la manière dont elle affecte l'apprentissage des étudiants ;

2. Les instructeurs doivent se présenter à l'atelier préparés à enseigner le matériel de l'atelier, ainsi qu'à répondre aux questions pertinentes liées à l'atelier ; 

3. Les instructeurs ne devraient **pas** lire la présentation uniquement pendant un atelier ;

4. Même pendant les instructions à distance, il est important que les instructeurs maintiennent une présence sociale dans le processus d'apprentissage. Les instructeurs doivent fournir un retour d'information, communiquer régulièrement, favoriser la participation et créer un environnement accueillant ;

5. Il a été démontré que les quiz en ligne sont plus efficaces que d'autres expériences d'apprentissage en ligne, comme l'attribution de devoirs (Ibid). Il faut donc veiller à consacrer du temps et à exécuter ces quiz quand le matériel de l'atelier le suggère ;

6. Les instructeurs devraient stimuler la collaboration chaque fois que cela est possible. Les étudiants engagés dans une expérience d'apprentissage social dirigée apprennent mieux, par opposition à un apprentissage isolé ;

7. Lorsque vous vous présentez, donnez un bref résumé de ce que vous faites et comment vous appliquez l'atelier de contenu dans votre travail ;

8. Faites une enquête rapide auprès de vos étudiants pour savoir dans quelle mesure ils ont une expérience du thème de l'atelier. Il s'agit d'une activité très utile qui peut vous aider à engager le dialogue avec les participants, leur permettre de discuter entre eux, vous aider à adapter une partie de votre atelier à votre public, vous renseigner sur votre rythme et sur le temps que vous réservez pour travailler sur les exercices ;

9. Demandez régulièrement aux participants s'ils ont des questions récurrentes sur le contenu, et permettez leur d'y répondre. Rassurez les participants en leur disant qu'ils peuvent lever la main et vous poser des questions pendant l'atelier. Si l'atelier se déroule à distance, assurez-vous que les participants comprennent comment utiliser le chat et lever la main dans Zoom ;

10. Chaque fois que vous posez des questions aux participants, il est avisé de ne pas demander uniquement des réponses aux volontaires, mais de "pointer" ou de "nommer" quelqu'un pour répondre à votre question.

## Directives pour l'assistance

Quand vous assumez le rôle d'assistant ou d'assistante pendant les ateliers :

1. Soyez attentifs et prêts à couper le son des participants qui ont laissé leur microphone allumé par inadvertance et qui émettent des bruits qui interfèrent avec les instructions de l'atelier ;

2. Communiquez avec les participants via le "chat" à propos de sujets liés à l'atelier ;

3. Répondre à toute question que les participants pourraient poser publiquement ou en privé dans le cadre de Zoom ;

4. Facilitez et stimulez la discussion dans les salles de conférence ("breakout rooms") en donnant des pistes de discussion et des conseils, soit avant d'ouvrir les salles ou pendant la période de discussion via un message "broadcast" ;

5. Prenez les présences, et contactez les participants non-inscrits pour leur demander de s'inscrire immédiatement à l'atelier. **Tous les participants doivent être inscrits** ;


## Aide à la présentation {#aide-presentation}

Vous pouvez accéder à l'option d'aide à la présentation en ouvrant une présentation et en appuyant sur `H` ou `?`. 

## Presenter mode {#mode-presentateur}

Le mode présentateur vous permet de visualiser les notes de présentation tout en donnant vos instructions. Pour accéder au mode présentateur, vous devez :

1. Ouvrir la présentation ; 
2. Cloner la présentation en appuyant sur `c`. Une fois que vous aurez fait cela, vous remarquerez qu'une nouvelle fenêtre apparaîtra et que tout ce que les deux fenêtres imitent l'une de l'autre, *i.e.*. ce qui signifie que si vous changez de diapositive dans l'une des deux, l'autre changera ; 
3. Entrer en mode présentateur dans l'une des fenêtres, en utilisant le raccourci clavier `p` ;
4. Notez que vous devez partager la fenêtre clonée qui n'est *pas* en mode présentateur avec les participants. Les détails sur la façon de procéder sont expliqués ci-dessous.   

## Directives pour Zoom {#conseils-zoom}

Organiser un atelier par Zoom n'est peut-être pas dans la zone de confort de chaque présentateur ou présentatrice. Voici quelques conseils pour vous aider à utiliser Zoom afin de créer une expérience d'atelier interactive et technologiquement fluide.

### Partager votre écran ou une fenêtre spécifique

Par défaut, l'autorisation de "partage d'écran" n'est généralement accordée qu'à l'hôte de la réunion. Cependant, vous pouvez attribuer des autorisations de partage à d'autres participants. **Nous vous recommandons de tester les options de "Partage d'écran" avant que les participants n'entrent dans la salle Zoom**.

Pour partager une fenêtre spécifique, cliquez sur le bouton **Partager l'écran** (en anglais, *Share Screen*) situé dans les commandes de votre réunion, et sélectionnez l'option **Fenêtre d'application spécifique** qui contient la présentation que vous allez partager avec les participants.

Pour partager tout votre écran, cliquez sur le bouton **Partager l'écran** (en anglais, *Share Screen*) situé dans les commandes de votre réunion, et sélectionnez l'option **Bureau** (en anglais, *Desktop*) qui correspond à votre atelier.

Pour plus d'informations sur le partage d'écran, veuillez consulter cette [page d'aide](https://athelp.sfsu.edu/hc/en-us/articles/360044278334-Sharing-your-screen-in-Zoom).

### Vie privée

Si vous souhaitez cacher votre arrière-plan pendant que vous présentez l'atelier, n'hésitez pas à utiliser un [arrière-plan virtuel](https://support.zoom.us/hc/en-us/articles/210707503-Virtual-Background) dans Zoom. Veuillez vous assurer que l'arrière-plan n'est pas une distraction, ne masque pas votre visage et respecte notre code de conduite.

### Gestion du "Chat"

**L'assistant de l'atelier doit garder un œil sur le "Chat" autant que possible**. Préparez-vous à répondre aux questions des participants et à vérifier comment ils se sentent, par exemple en leur demandant périodiquement s'ils aimeraient faire une courte pause, s'ils ont besoin de plus de temps pour faire des exercices ou s'ils veulent plus d'explications. Veuillez noter que vous pouvez choisir d'envoyer un message à **tout le monde** ou de discuter avec un participant spécifique **en privé**.

Si un participant a des difficultés avec l'atelier et a besoin d'une aide supplémentaire, **l'assistant amener ce participant (ou plusieurs participants) dans une salle de réunion pour fournir des explications plus complètes et/ou du dépannage**. Voir les informations sur les salles de réunion ci-dessous.

**Veuillez enregistrer le Chat, si possible, et le partager avec les participants lorsque vous les contacterez après l'atelier.**

### Retours non verbaux

Vous pouvez également demander des retours non verbaux à votre public par le biais de [Réactions](https://support.zoom.us/hc/en-us/articles/360038311212-Meeting-reactions). C'est un excellent moyen de faire le point avec les participants et de demander une Réaction spécifique si les informations ne sont pas claires, ou si ils ont terminé un exercice. Il existe [des fonctionnalités supplémentaires de retours](https://www.pitzer.edu/information-technology/services/zoom/manage-participants/) dans le panel **Participants**, notamment **Raise Hand**, **Oui** et **Non**, entre autres.

N'hésitez pas à utiliser la fonctionnalité avec laquelle vous êtes le plus à l'aise, mais veillez à expliquer comment accéder à ces fonctionnalités dans la section "Bienvenue" de l'atelier.

### Sondages

Certains des exercices de l'atelier sont conçus sous forme de simples sondages. Pour les ateliers à distance, ces sondages seront effectués sur Zoom.

**Veuillez préparer les sondages avant le début de l'atelier**, afin d'assurer le bon déroulement des exercices. Les questions et réponses des sondages sont disponibles dans les [présentations](https://r.qcbs.ca/fr/workshops/). Vous pouvez voir **comment créer et lancer des sondages dans Zoom [ici](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-meetings#h_fe37b3f4-8e05-4b87-bd66-12d8c7f19ff8)**.

### Salles de conférence

Certains des exercices de l'atelier sont conçus pour être effectués en groupe. Pour les ateliers à distance, ces exercices de groupe auront lieu dans des salles de conférence ("Breakout Rooms").

**Veuillez noter que par défaut, l'hôte de la réunion est la seule personne qui peut assigner des participants aux salles de conférence**, et le premier présentateur à entrer dans la salle sera assigné comme hôte. Gardez cela en tête, et entrez dans la salle en premier (c'est-à-dire en avance!) si vous êtes responsable des salles de conférence.

#### Création de salles de conférence

1.  Vous devriez voir l'option pour les **salles de conférence ("Breakout Rooms")** en bas à droite de votre barre d'outils **Zoom**. Cliquez sur ce bouton.

2.  Vous verrez une **fenêtre pop-up dans laquelle vous pouvez assigner des participants à un certain nombre de salles, que vous pouvez définir vous-même**. En bas de cette fenêtre, vous trouverez une estimation du nombre de participants par salle, basée sur le nombre de salles. Essayez de choisir un nombre de salles qui donne **3 à 5 personnes par salle**. Cochez la case "Automatiquement" pour que Zoom assigne arbitrairement les participants aux salles de conférence.

3.  Une fois que les participants sont assignés aux salles de conférence, cliquez sur le bouton **""Start All Sessions"**.

#### Communication avec les participants

Veuillez noter que les **participants ne peuvent pas accéder au Chat une fois qu'ils sont dans les salles de conférence**. Si vous avez des informations à communiquer, telles que les objectifs de l'exercice ou des liens, veuillez le faire avant d'ouvrir les salles de conférence. Il est également conseillé de préciser aux participants le temps que vous leur accordez pour l'exercice avant qu'ils se joignent à leur salle.

Vous pouvez communiquer avec les participants dans les salles de conférence en **diffusant un message à tous ("Broadcast message to all")**, qui est un bouton dans le panneau des salles de conférence qui est à la disposition de la personne qui a créé les salles.

Les hôtes et co-hôtes peuvent également se joindre à des salles de conférence individuelles pour se renseigner sur les différents groupes, si vous le souhaitez [(instructions ici)](https://elearning.uq.edu.au/guides/virtual-classroom/moving-between-breakout-rooms).

#### Fermer les salles de conférence

4.  Cliquez sur le bouton **"Stop All Sessions"** dans le panneau des salles de conférence qui est à la disposition de la personne qui a créé les salles.

Pour plus d'informations sur la mise en place des salles de conférence, reportez-vous à ce [guide visuel](http://web5.lib.pacificu.edu/zoom/how-to-use-breakout-rooms/) et au [guide de Zoom](https://support.zoom.us/hc/en-us/articles/206476313).

## Contribuer à ces directives

Avez-vous des suggestions concernant ces directives? Veuillez [créer un numéro](https://github.com/QCBSRworkshops/presenter-developer-protocol/issues) et nous aider à améliorer ce matériel !