# (PART) English version {-}

# Code of conduct {#codeofconduct}

The **QCBS R Workshop Series** and the **QCBS R Symposium** are venues dedicated to providing a welcoming and supportive environment for all people, regardless of background or identity.

Participants, presenters and organizers of the workshop series and other related activities **accept** this Code of Conduct when being present at any workshop-related activities.

*We do not tolerate behaviour that is disrespectful or that excludes, intimidates, or causes discomfort to others.*

We do not tolerate discrimination or harassment based on characteristics that include, but are not limited to, gender identity and expression, sexual orientation, disability, physical appearance, citizenship, ethnic or social origin, pregnancy, familial status, religion or belief (or lack thereof), membership of a minority, age, education and socioeconomic status.

It applies to all spaces managed by or affiliated with the workshop, including, but not limited to, workshops, email lists, and online forums such as GitHub, Slack and Twitter.

Workshop participants violating these rules may be sanctioned or expelled from the workshop without a refund at our discretion.

#### Expected behaviour {-}

All participants and presenters are expected to show respect and courtesy to others. All interactions should be professional regardless of platform: either online or in-person. In order to foster a positive and professional learning environment we encourage the following kinds of behaviours in all workshop events and platforms:

* Use welcoming and inclusive language
* Be respectful of different viewpoints and experiences
* Gracefully accept constructive criticism
* Focus on what is best for the community
* Show courtesy and respect towards other community members

#### Unacceptable behaviour {-}

Examples of unacceptable behaviour by participants at any workshop event/platform include:

* written or verbal comments which have the effect of excluding people on the basis of membership of any specific group;
* causing someone to fear for their safety, such as through stalking or intimidation;
* violent threats or language directed against another person;
* the display of sexual or violent images;
* unwelcome sexual attention;
* nonconsensual or unwelcome physical contact;
* insults or put-downs;
* sexist, racist, homophobic, transphobic, ableist, or exclusionary jokes;
* incitement to violence, suicide, or self-harm;
* continuing to initiate interaction (including photography or recording) with someone after being asked to stop;
* publication of private communication without consent.

If a participant or a presenter engages in harassing behaviour, we may take any action we deem appropriate, including warning the offender or expulsion from the workshop without a refund. Participants and presenters asked to stop any harassing behaviour are expected to comply immediately.

If you are being harassed, notice that someone else is being harassed, or have any other concerns, please contact one of the workshop organizers immediately.
