# Presentation {#presentation-en}

The following recommendations have been written to improve the delivery of workshop content to participants. We propose guidelines based on evidence-based strategies for teaching and learning. Even though a few aspects might be basic to you, we ask you to read them all carefully.

## Workshop structure

On average, in-person workshops last 4 hours (including breaks), with some variability depending on the content and workshop complexity.

*Remote workshops* should run for approximately 3 hours. Workshops are being shortened to suit this new format. Generally, we propose that the instruction time be broken into two 1.5 hour sections, with a one-hour break in between. However, some workshops may benefit from a different flow, *e.g.* two breaks of 30 minutes instead of a long one-hour break. *Suggestions for Workshops 1 to 5 are provided below.*

Each workshop should begin with a welcome and check-in period lasting around 5 minutes. During this time, workshop presenters and assistants may take attendance, ask participants how they are doing, and give participants instructions on how to use the Chat and make questions.

Following the welcome and check-in period, workshop presenters should begin their lecture blocks by illustrating and specifying the content of the workshop and how the lecture and pauses will be structured.

> During both remote and in-person workshop contexts, additional short breaks of 5 to 10 minutes (each) should be occasionally provided to allow participants and presenters to take a short pause and to address any outstanding questions.

At the end of the workshop, presenters and assistants should thank the participants for being present, request participants to fill the feedback survey, and allow them to ask questions (if time allows).

Suggestions for workshop schedules for Workshops 1 to 5:

|                Blocks|   Workshop 1  |     Workshop 2|   Workshop 3  |     Workshop 4|  Workshop 5|
|---------------------:|:-------------:|--------------:|:-------------:|--------------:|-----------:|
|  Welcome and check-in|   5 minutes   |      5 minutes|   5 minutes   |      5 minutes|   5 minutes  |
|         Lecture block|   85 minutes  |     85 minutes|   85 minutes  |     55 minutes|  55 minutes  |
|                 Pause|   60 minutes  |     60 minutes|   60 minutes  |     30 minutes|  30 minutes  |
|         Lecture block|   85 minutes  |     85 minutes|   85 minutes  |     60 minutes|  85 minutes  |
|                 Pause| *Not applic.* |  *Not applic.*| *Not applic.* |     30 minutes| *Not applic.*|
|         Lecture block| *Not applic.* |  *Not applic.*| *Not applic.* |     55 minutes| *Not applic.*|
|      Wrap-up and exit|   5 minutes   |      5 minutes|   5 minutes   |      5 minutes|   5 minutes  |

## General guidelines

During the day of the workshop, both workshop instructors and assistants must:

1.  Arrive *at least* 15 minutes before the beginning of your workshop to prepare the presentation room and project your presentation.

-   For remote workshops, please open the meeting room early (along with the presentation, wiki and RStudio) and check-in with your co-presenter before participants arrive;

2.  Take attendance;

3.  Collect receipts from non-members;

4.  Start your presentation **on time**.

## Presenting guidelines

1.  Instructors should consider themselves students during the learning process, and be thoughtful on their method of delivery and communication, and how it affects student learning;

2.  Instructors must come to workshop prepared to instruct the workshop material, as well as to respond to relevant questions related to the workshop;

3.  Instructors should **not** only read the presentation during a workshop;

4.  Even during remote instructions, it is important that instructors maintain social presence in the learning process. Instructors should provide feedback, communicate regularly, model participation, and create an inviting tone;

5.  Online quizzes have been shown to be more effective than other online learning experiences, such as assigning homework (Ibid). Thus, be sure to allocate time and execute these quizzes whenever suggested by the workshop material;

6.  Stimulate collaboration whenever possible. Students engaged in a directed, social learning experience learn better, as opposed to isolated learning;

7.  When introducing yourselves, give a short summary about what you do and how do you apply the content workshop in your work;

8.  Do a quick survey of your students to see how much experience they have with the workshop topic. This is a great activity that can help you engage with participants, allow them to discuss with each other, help you cater part of your workshop to your audience, inform your delivery speed, and the amount of time you set aside to work through exercises;

9.  Regularly ask participants if they have recurring questions about the content, and allow them to be addressed. Reassure attendants that they can raise their hands and pose questions to you during the workshop. If the workshop is remote, make sure students understand how to use the Chat and raise their hand in Zoom;

10. Whenever asking questions to participants, it is a good practice to not only request responses from volunteers, but to "point" or "name" someone to respond to your question.

## Assisting guidelines

Whenever you take the role as an assistant during the workshops, you should:

1.  Be attentive and prepared to mute participants that have inadvertently left their microphones turned on and that are making noises that are interfering with the workshop instruction;

2.  Communicate with participants through the Chat with subjects related to the workshop;

3.  Respond to any questions that participants may publicly or privately pose within Zoom;

4.  Assist and stimulate discussion within Breakout Rooms by giving discussion points and tips, either before opening the Breakout Rooms, or by sending a "broadcast" message to participants within the rooms;

5.  Take attendance, and reach out to non-registered participants to request them to immediately register to the workshop. **Everyone attending must be registered**;

## Presentation help {#presentation-help}

You can access the presentation help option by opening a presentation and pressing `H` or `?`. 

## Presenter mode {#presenter-mode}

Entering presenter mode allows you to view presentation notes while giving your instruction. To access presenter mode, you must:

1. Open the presentation; 
2. Clone the presentation by pressing `c`. Once you do this, you will notice that a new window will pop-up and that anything that both windows mimic each other, *i.e*. meaning that if you change the slide in one of the, the other will change;  
3. Enter presenter mode in one of the windows, by using the keyboard shortcut `p`;
4. Note that you must share the cloned window that is *not* in presenter mode to participants. The details on how to do this are explained below.   

## Zoom guidelines {#zoom-guidelines}

Running a workshop through Zoom might not be within every presenter's comfort zone. Here are some guidelines to help with the process of using Zoom to create a (hopefully!) technologically smooth and interactive workshop experience.

### Sharing your screen or a specific window

By default, "Share Screen" permission is usually given only to the meeting host. However, you can assign sharing permissions to other participants. **We recommend testing out the "Screen Sharing" options before participants enter the Zoom room**.

To share a specific window, click the **Share Screen** button located in your meeting controls, and select the **Specific application window** option that contains the presentation you will share to participants.

To share your entire screen, click the **Share Screen** button located in your meeting controls, and select the **Desktop** option that is relevant to your workshop.

For more information about how to share your screen, please consult this [help page](https://athelp.sfsu.edu/hc/en-us/articles/360044278334-Sharing-your-screen-in-Zoom).

### Privacy

If you would like to hide your background while you are presenting the workshop, feel free to use a [virtual background](https://support.zoom.us/hc/en-us/articles/210707503-Virtual-Background) in Zoom. Please make sure the background is not distracting, does not obscure your face, and follows our code of conduct.

### Moderating the Chat

**The workshop assistant should keep an eye on the Chat as much as possible**. Prepare to answer participants' questions and to check in with how the participants are feeling, such as periodically asking if people would like a short break, if they need more time for exercises, or if they would like more explanation. Please note you can choose to message **Everyone** or chat with a specific participant **Privately**.

If a participant is having trouble with the workshop and needs additional help, **the assistant can pull this participant (or several participants) into a Breakout Room to provide more thorough explanations and troubleshooting**. See information about Breakout Rooms below.

**Please save the Zoom chat, if possible, and share it with the participants when you contact them after the workshop.**

### Non-verbal feedback

You can also ask for nonverbal feedback from your audience through [Reactions](https://support.zoom.us/hc/en-us/articles/360038311212-Meeting-reactions). This is a great way to check in with workshop participants and ask for a specific Reaction if things are unclear, or if they are finished with an exercise. There are [additional feedback features](https://www.pitzer.edu/information-technology/services/zoom/manage-participants/) in the **Participants** panel, including **Raise Hand**, **yes**, and **no**, among others.

Feel free to use whichever feature you are most comfortable with, but please ensure that you explain how to access these features during the Welcome section of the workshop.

### Polls

Some of the workshop exercises are designed as simple polls. For remote workshops, these polls will be set up in Zoom.

**Please set up the polls before the workshop begins**, to ensure the exercises run smoothly. Poll questions and answers are available in the [presentations](https://r.qcbs.ca/workshops/). You can review **how to create and launch polls in Zoom [here](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-meetings#h_fe37b3f4-8e05-4b87-bd66-12d8c7f19ff8)**.

### Breakout Rooms

Some of the workshop exercises are designed to be done in groups. For remote workshops, these group exercises will take place in Breakout Rooms.

**Please note that by default, the meeting host is the only person who can assign participants to Breakout Rooms**, and the first presenter to enter the room will be assigned as host. Please keep this in mind, and enter the room first (i.e. early!) if you are in charge of Breakout Rooms.

#### Creating Breakout Rooms

1.  You should see the option for Breakout Rooms on the lower right side of your **Zoom toolbar**. Click this button.

2.  You will see a **pop-up window where you can assign participants to certain number of rooms, which you can set yourself**. At the bottom of this window, there is an estimated number of participants per room, based on the number of rooms. Try to choose a number of rooms that results in **3 to 5 people per room**. Keep the assignment process check-marked as "Automatically", so Zoom arbitrarily assigns participants to Breakout Rooms.

3.  Once participants are assigned to Breakout Rooms, click the **"Start All Sessions"** button.

#### Communicating with participants in Breakout Rooms

Please note that **participants cannot access the Chat once they are in Breakout Rooms**. If you have information to communicate, such as the exercise objectives or links, please do so before you open the Breakout Rooms. It is also a good idea to let people know how much time you are giving them for the exercise before they join their rooms.

You can communicate with participants in the Breakout Rooms by **broadcasting a message to all**, which is a button within the Breakout Rooms panel that is available to the person who has created the rooms.

Hosts and co-hosts can also join individual Breakout Rooms to check in on different groups, if you choose to do so [(instructions here)](https://elearning.uq.edu.au/guides/virtual-classroom/moving-between-breakout-rooms).

#### Closing Breakout Rooms

4.  Click the **"Stop All Sessions"** button in the Breakout Rooms panel that is available to the person who has created the rooms.

For more information about setting up Breakout Rooms, refer yourself to this [visual guide](http://web5.lib.pacificu.edu/zoom/how-to-use-breakout-rooms/) and to [Zoom's guide](https://support.zoom.us/hc/en-us/articles/206476313).

## Contributing to these guidelines

Do you have any suggestions on these guidelines? Please [raise an issue](https://github.com/QCBSRworkshops/presenter-developer-protocol/issues) and help us improve this material!
