# Presentation {#presentation-en}

The following recommendations have been written to improve the delivery of workshop content to participants. We propose guidelines based on evidence-based strategies for teaching and learning. Even though a few aspects might be basic to you, we ask you to *carefully* read them.

## Workshop structure

On average, in-person workshops last 4 hours (including eventual breaks), with some variation depending on the length of the workshop content and with its complexity.

*Remote workshops* should run for approximately 3 hours. Workshops are being shortened to suit this new format. Usually, the instruction time is proposed to be broken into two 1.5 hour sections, with a long one-hour break in middle. Nevertheless, some workshops may benefit from a different flow, *e.g.* two breaks of 30 minutes instead of a long one-hour break.

Each workshop should begin with a welcome and check-in block lasting around 5 minutes. In this period, workshop presenters and assistants may take attendance, tell participants how you are doing and allow participants to do the same, and give participants instructions on how to use the chat and make questions.

Following the welcome and check-in block, workshop presenters should begin their lecture blocks by illustrating and specifying the content of the workshop and how the lecture and pause blocks will be structured.

> During both remote and in-person workshop contexts, additional short breaks of 5 to 10 minutes (each) should be occasionally provided to allow participants and presenters to take a short pause and to address any outstanding questions.

At the end of the workshop, presenters and assistants should thank the participants for being present, request participants to fill the feedback survey, and allow them to ask questions (if time allows).

See the proposed format below for the workshop schedules:

|     Blocks    |  Workshop 1    | Workshop 2 |  Workshop 3 | Workshop 4 | Workshop 5 |
| -------------:|:-------------:| ----------:|:-------------:| ----------:| ----------:|
| Welcome and check-in | 5 minutes   |    5 minutes       | 5 minutes  | 5 minutes | 5 minutes |
| Lecture block | 85 minutes   |    85 minutes       | 85 minutes       |    85 minutes      | 55 minutes  |
| Pause  | 60 minutes      |    60 minutes      |60 minutes      |    60 minutes      | 30 minutes |
| Lecture block | 85 minutes   |    85 minutes       | 85 minutes       |    85 minutes      | 85 minutes  |
| Pause  | *Not applic.* |    *Not applic.*      | *Not applic.*  |    *Not applic.*  | 30 minutes |
| Lecture block | *Not applic.*   |    *Not applic.*       | *Not applic.*  | *Not applic.* | 55 minutes  |
| Wrap-up and exit | 5 minutes   |    5 minutes       | 5 minutes  | 5 minutes | 5 minutes  |

## General guidelines

During the day of the workshop, you must:

1. Arrive *at least* 15 minutes before the beginning of your workshop to prepare the presentation room and project your presentation. For remote workshops, open the meeting room early and check-in with your co-presenter before participants arrive;

2. Take attendance;

3. Collect receipts from non-members;

4. Start your presentation **on time**.

## Workshop presenting guidelines

1. Instructors should consider themselves students during the learning process, and be thoughtful on their method of delivery and communication, and how it affects student learning;

2. Instructors must come to workshop prepared to instruct the workshop material, as well as to respond to relevant questions related to the workshop; 

3. Instructors should **not** only read the presentation during a workshop;

4. Even during remote instructions, it is important that instructors maintain social presence in the learning process. Instructors should provide feedback, communicate regularly, model participation, and create an inviting tone;

5. Online quizzes have been shown to be more effective than other online learning experiences, such as assigning homework (Ibid). Thus, be sure to allocate time and execute these quizzes whenever suggested;

6. Stimulate collaboration whenever possible. Students engaged in a directed, social learning experience learn better, as opposed to isolated learning;

7. When introducing yourselves, give a short summary about what you do and how do you apply the content workshop in your work;

8. Do a quick survey of your students to see how much experience they have with the workshop topic. This is a great activity that can help you engage with participants, allow them to discuss with each other, help you cater part of your workshop to your audience, inform your delivery speed, and the amount of time you set aside to work through exercises;

8. Once every few minutes, ask participants if they have recurring questions about the content, and allow them to be addressed. Reassure attendants that they can raise their hands and pose questions to you during the workshop. If the workshop is remote, make sure students understand how to use the chat and raise their hand in Zoom;

9. Whenever asking a specific question to participants, it is a good practice to not only request volunteers, but to "point" or "name" someone to respond to your question.

## Workshop assistant guidelines

Whenever you take the role as an assistant during the workshops, you should:

1. Be attentive and prepared to mute participants that inadvertently left their microphones turned on and that are making noises that are interfering with the workshop instruction;

2. Communicate with participants through the chat with subjects related to the workshop;

3. Respond to eventual questions that participants may publicly or privately pose within Zoom;

4. Assist and stimulate discussion within breakout rooms;

5. Take attendance, and reach out to non-registered participants to request them to imemdiately register to the workshop.

## Contributing to these guidelines

Do you have any suggestions on these guidelines? Please [raise an issue](https://github.com/QCBSRworkshops/presenter-developer-protocol/issues) and help us improve this material!