# Receiving your award {#payment-en}

All workshop presenters receive a **Learning and Development Award** from the **Québec Centre for Biodiversity Science (QCBS)**.

You must follow these steps to receive your award payment:

1. **First, complete the [payment sheet](https://docs.google.com/spreadsheets/d/1Vu566MpuwtEoSrTpobrAPdVBmwi-AHP1lEb9lhv0Uc8/edit?usp=sharing)**. You can refer to the [compensation standards](#preparation-en) section within this protocol to know the budget allocated to your workshop. *Remember that each presenter receives an award of a maximum of $125 per workshop instructed*.

2. **Second, complete and sign this [form](https://www.mcgill.ca/financialservices/files/financialservices/employee_or_selfemployes_20120815_questionnaire_en.pdf)**. Note that you are considered as a “*Payee*” for the purposes of the development and instruction of a workshop belonging to the QCBS R Workshop Series. If you need more infromation on the determination of employee versus self-employed or independent contractor, go to [here](https://www.mcgill.ca/financialservices/policies/emplself#pr2-determination-of-employee-vs-self-employed-independent-contractor). Name your file to "`YOURLASTNAME_PayeeForm.pdf`".

3. **Third, fill out the QCBS [invoice](https://github.com/QCBSRworkshops/presenter-developer-protocol/blob/master/YOURNAME_Invoice.docx?raw=true)**. 

  * You must write your *name*, *e-mail*, *phone number*, *complete address* (including postal code, city and province), *total balance* and *description of your work* (e.g., "Description: Lead presenter of workshops 1 and 2"; "Unit Cost: $ 125 per workshop"; "Total: $ 250"). 
  
  * For the moment, do not write anything next to "P.O." (which stands for Purchase Order).
  
  * Name your invoice to "`YOURLASTNAME_RWorkshop_Invoice.docx`".

4. **Fourth, send both the form and the invoice to [helen.elina@mcgill.ca](mailto:helen.elina@mcgill.ca)** (Helen Elina is the Administrative Associate of the QCBS). If you have already been registered as an employee or a self-employed, independent contractor for the McGill University, please indicate it within the message you send to Dr. Elina. You can use the following message model for your message:

> Message subject: Learning and Development Award - QCBS R Workshop Series

> Dear Dr. Elina,
>
> You will find attached to this message my payee form and the invoice concerning the workshop(s) that I instructed as part of the QCBS R Workshop Series.
>
> I HAVE NOT or I HAVE BEEN registered as an employee or a self-employed, independent contractor for the McGill University.
>
> I certify that the information attached to this message is true and correct to the best of my knowledge.
>
> With kind regards,
>
> YOUR NAME


5. After a few weeks, McGill University's Procurement Services will send you an e-mail containing a purchase order. 

* You must **copy the purchase order number** and paste it to the fields *Purchase Order* and *Invoice Number* of the invoice that you sent to Helen.

* It is *really important* that you change the *Invoice Number* accordingly, otherwise your payment will not be processed.

6. **Export the invoice to PDF**, and send it to [**accountspayable@mcgill.ca**](mailto:accountspayable@mcgill.ca). You should receive a cheque in the address you included within your invoice.

To prevent any delays, please double-check your information and confirm that all fields concerning yourself are filled within both forms.

