# Frequently Asked Questions (FAQ) {#faq-en}

#### **Award eligibility and contributing to the series** {-}

1. Am I eligible to receive a **Le**arning **a**nd **D**evelopment **A**ward (LeaDA)? 

> To receive a Learning and Development Award (LeaDA), you must be an active QCBS member (i.e. at least one of your supervisors must be a member of the QCBS) AND must NOT be a postdoctoral fellow from McGill University.

2. I am a postdoctoral fellow from McGill University. Why am I ineligible for a **Le**arning **a**nd **D**evelopment **A**ward (LeaDA)?

> Unfortunately, because of institutional and contractual limitations, the QCBS is being prevented from offering awards to McGill postdoctoral fellows. In rare circumstances, McGill postdoctoral fellows might have contractual freedom with their principal investigators to receive such awards. We recommend that you contact your principal investigator to discuss this, and then contact the [coordinators of the R Workshop Series]() and [Philippe Auzel]() to discuss these exceptions.

3. I would like to contribute by developing a workshop. How can I do it?

> Thank you for your interest in contributing to the workshop series! We regularly send messages and make [Facebook](https://www.facebook.com/groups/csbq.qcbs/) and [Twitter](https://twitter.com/Csbq_qcbs_stu) posts inviting developers to think critically and apply improvements to the workshop. To make sure we will keep you on the loop, you can begin by filling [this questionnaire]() about which workshops(s) you would like to contribute. All invited contributors to the series are eligible to receive a Learning and Development Award!

4. How can I contribute by instructing a workshop?

> Workshops are currently instructed during the Fall and during the Winter. We regurlaly send messages and make [Facebook](https://www.facebook.com/groups/csbq.qcbs/) and [twitter](https://twitter.com/Csbq_qcbs_stu) posts inviting QCBS members to instruct one or more workshops for the R Workshop Series. If you are an active member of the QCBS, you will receive a message around September and October for the Fall workshops, and around December and January for the Winter workshops. Stay tuned! All instructors for the QCBS R Workshop Series are eligible to receive a Learning and Development Award from the QCBS.

5. I am not proficient in `R`, `RMarkdown`, and/or `Github`. Can I still help?

> It is not mandatory to be proficient in `R`, `RMarkdown`, and/or `Github` in order to contribute to the development or instruction of the workshops. The **Le**arning **a**nd **D**evelopment **A**wards (LeaDAs) are aimed to provide training and learning opportunities for QCBS members which means that contributing to the workshops can be an opportunity for members to learn and improve their `R`, `RMarkdown`, and/or `Github` skills. However, we do reccomend that members interested in contributing to the series should have attended the workshops they wish to contribute to as participants so that they are at least familiar with the topic of the workshop.

#### **Pre-Workshop Questions** {-}

1. What do I need to prepare for the workshop?

> You must take your time to carefully read and apply the guidelines within the [Preparation section](#preparation-en). Those instructions have been carefully developed with the evidence, recommendations and experience from coordinators, presenters and participants across several years, and concisely written for you, so your experience and the experience of participants can go in the best way as possible. If you have any questions or recommendations, please [contact the coordinators]().

2. When instructing workshops, do we have to stick to the workshop material?

> *Yes* and *no*. You may replace the workshop material (presentation and book) that we provide for you by an independent option. Additionally, if time allows, feel free to recommend and use additional tools and information. If you believe that the workshops could be improved and benefit from any additional material, please create an issue in their corresponding Github repositories!

3. I have never instructed an online workshop. Where should I begin?

> Besides the general presenter preparation guidelines available in the [Preparation section](#preparation-en), we have provided additional detailed guidelines for remote workshops [here](#zoom-guidelines). There is 

4. Can I invite my friend or my colleague to participate in a workshop?

> Yes, but they *must be* officially registered to the workshop. Even if last minute, ask them to [register to the workshop](https://qcbsrworkshops.github.io/pricing/) before providing them with the information to join the workshop venue.

5. I am instructing a workshop. How do I get in touch with the participants?

> Two weeks before the workshop, we will provide you with the code you will need in order to obtain the list of participants. You can then contact them using the standardized messages we have prepared in the presenter protocol (see the [Preparation section](#preparation-en)).

#### **Workshop Questions** {-}

1. I feel that someone is being disrespectful to me or to the other participants. What should I do?

> We do not tolerate behaviour that is disrespectful or that excludes, intimidates, or causes discomfort to others. Workshop participants violating these rules may be sanctioned or expelled from the workshop without a refund at our discretion. If you are being harassed, notice that someone else is being harassed, or have any other concerns, please contact one of the workshop organizers immediately.


2. I have seen bugs and errors when preparing or when presenting a workshop. What happened?

> The QCBS `R` Workshop Series is constantly being improved by members of the QCBS as learning and developing opportunities. While we attempt to provide workshop materials that allow for the best learning and teaching experience for materials, it is possible that bugs and errors were overseen during the yearly development. We appreciate all the feedback instructors and participants provide and we use it to continue improving the workshops every year.

3. How can I report bugs and errors in the workshop materials?

> We ask all presenters to fill out the [presenter feedback form](https://goo.gl/forms/85TXCiQ9tW9nvq922) for the workshop they just instructed where you can let us know about any improvements that should be made for next year's workshop. Additionally, if you have more specific feedback about the presentation slides or the book content such as mistakes or inconsistencies, or if you would like to make any other suggestions about the workshop form or content, you are invited to open an issue on the [GitHub](https://github.com/QCBSRworkshops) repository for the workshop in question. If you do not have a GitHub account, or are not comfortable with GitHub, please contact the workshop coordinators directly with your feedback.

#### **Payment Questions** {-}

1. What is the **Le**arning **a**nd **D**evelopment **A**ward (LeaDA)?

> The <a href = "https://qcbs.ca/student-grants/learning-development-award-leada">Learning Development Award (LeaDA)</a> is available to graduates student and post-doctoral QCBS members, who propose substantial contributions towards the training and learning experience of graduate students and faculty beyond established academic courses within the QCBS network. The QCBS offers Learning and Development Awards to support graduates student and post-doctoral QCBS members who instruct or develop workshops. 

2. How much is the award I am going to receive?

> In September 2021, the Learning and Development Award amounts to $150 for each contribution from instructors or developers of the R Workshop Series. Because Non-McGill contributors are subject to federal and provincial taxes on the awards they receive, a 27.53% surplus will be added to this amount to compensate for the taxes they pay.

3. How can I receive my award?

> LeaDA are processed according to several steps outlined in the [Receiving your award](#payment-en) section of this protocol. Please ensure that you have completed all the steps required for your institution and affiliation status. If you do not receive any notification that your payment is being processed within a maximum of 45 days, please contact Dr. Elina (<helen.elina@mcgill.ca>), the Administrative Associate of the QCBS, to follow up on your award request.

4. I instructed or developed a workshop, submitted my payment request, but have not been paid yet. What should I do?

> LeaDA are processed according to several steps outlined in [Receiving your award](#payment-en). **Please note that the LeaDA are processed differently according to institution and affiliation status.** First, please ensure that you have completed all the steps required for your institution and affiliation status. If you have followed these steps and are experiencing delays beyond the maximum timeframe for your institution and affiliation status, please contact Helen Elina ([helen.elina@mcgill.ca](mailto:helen.elina@mcgill.ca)), who is the Administrative Associate of the QCBS, so she can help you receive your payment. 

5. What are my tax obligations with respect to the award?

> Stipends and independent contracts are not employee wages and the payer (QCBS) is *not* responsible for any income tax or employment related deductions. Please carefully read the section on [Tax implications](#payment-en-tax-implications) to understand your legal and tax obligations.


#### **General Questions**{-}

1. Who are the coordinators of the series?

> The series is currently coordinated by Pedro Henrique P. Braga, Esteban Góngora, Katherine Hébert, and Linley Sherin.


2. Can I use the QCBS `R` Workshop Series to instruct workshops in my university?

> The QCBS `R` Workshop Series is copyrighted under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0) license. Under this license, you are allowed to share and adapt the content of the workshops for non-commercial purposes as long as you give appropriate credit to the QCBS `R` Workshop Series and you distribute your version of the material under the same license as the original. You can find more information on the license terms and conditions, you can visit this [link](https://creativecommons.org/licenses/by-nc-sa/4.0/).