--- 
title: "Presenter and Developer Protocol"
author: "QCBS R Workshop Series"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: 
  bookdown::gitbook:
    config:
      toc:
        collapse: subsection
        scroll_highlight: yes
        before: |
          <li><a href="...">QCBS R Workshop Series</a></li>
documentclass: book
bibliography: ["book.bib", "packages.bib"]
biblio-style: apalike
link-citations: yes
description: "This is the Presenter and Developer Protocol for the QCBS R Workshop Series"
---

```{r}
library(knitr)
opts_chunk$set(tidy.opts=list(width.cutoff = 60),
               tidy=TRUE)
```

# Protocole pour la présentation et le development {-}

Merci de faire partie de la série d'ateliers R du CSBQ !

Nous sommes heureux de vous avoir dans notre équipe !

Ce document regroupe les responsabilités des instructeurs, des instructrices, des développeurs et des développeuses des atelier R du CSBQ. Il vous guide à travers les tâches à effectuer avant, pendant et après les éditions et les instructions des ateliers. Cela vous aidera également à compléter les étapes pour recevoir votre prix d'excellence.

Nous vous demandons de bien vouloir lire toutes les instructions **très** attentivement !

Pour tout problème, veuillez communiquer avec l'équipe de coordination de la [série d'ateliers R du CSBQ](https://wiki.qcbs.ca/r#questions).

#### Contributions {-}

Ce protocole a été intégré dans ce livre afin d'inclure des directives claires et spécifiques pour présenter, développer et recevoir des prix d'apprentissage et de développement. Son développement a été fait par [Pedro Henrique Pereira Braga](mailto:ph.pereirabraga@gmail.com), [Katherine Hébert](mailto:katherine.hebert@usherbrooke.ca), [Linley Sherin](mailto:linley.sherin@mail.mcgill.ca) et a été basé sur sur le protocole original de présentation. Ce protocole est constamment maintenu et mis à jour par l'[équipe actuelle de coordination de la série d'ateliers R du CSBQ](https://wiki.qcbs.ca/r#questions).

---

## Presenter and Developer Protocol {-}

Thank you for being part of the QCBS R Workshop Series!

We are happy to have you in our team!

This document brings together the responsibilities of QCBS R Workshop presenters and developers. It walks you through the tasks needed to complete before, during and after instructing or developing workshops. It will also walk you through the steps to receive your award.  

We kindly ask you to read all instructions **very** attentively!

For any issues, please communicate with the [current workshop coordinators](https://wiki.qcbs.ca/r#questions).

#### Contributions {-}

This protocol has been built into this book to include clear and specific guidelines to present, to develop and to receive learning and development awards. Its development was done by [Pedro Henrique Pereira Braga](mailto:ph.pereirabraga@gmail.com), [Katherine Hébert](mailto:katherine.hebert@usherbrooke.ca), and [Linley Sherin](mailto:linley.sherin@mail.mcgill.ca), and it was based on the original presenter protocol. This protocol is constantly maintained and updated by the [coordinators of the QCBS R Workshop Series](https://wiki.qcbs.ca/r#questions).