The package [qcbsRworkshops](https://github.com/QCBSRworkshops/qcbsRworkshops)
was originally designed as a set of functions to check whether the workshops can
be correctly built on [Travis CI](https://travis-ci.org/). While working on thi
s package,it turned out to be quite helpful to develop/improve the workshops.
The main features of `qcbsRworkshops` are detailed below. 



## Installation 

To install `qcbsRworkshops`, use the [`remotes`](https://CRAN.R-project.org/package=remotes) (dependency of [`devtools`](https://CRAN.R-project.org/package=devtools)).

```R
install.packages(remotes)
remotes::install_github("QCBSRworkshops/qcbsRworkshops")
```

Note that by installing `qcbsRworkshops` a set of packages will be installed,
including [`xaringan`](https://CRAN.R-project.org/package=xaringan). Once
installed, load it just as you would do for any package. 

```R 
library(qcbsRworkshops) 
``` 

Note that, as any other R package, the functions of the package `qcbsRworkshops`
are documented. Therefore, if you ever need more details about a specific
function, just use the question mark, e.g. `?download_workshops`.



## Download a workshop 

Once the package loaded, you can quickly download a package with
`download_workshops()`, you simply need to use the identifier (`id`) of the
desired workshop (1 for the first workshop, 2 for the second and so forth). 

```R 
download_workshops(id = 1)
```


This actually downloads a zip file from GitHub that includes the sources files
of the workshop, so the English and the French version of the workshop. By
default, the files will be extracted in the working directory. This can be
changed by setting `path` to the desired path. Note that `download_workshops()`
also supports vectors of identifiers, for instance, the following code will
download all workshops : 

```R 
download_workshops(id = 1:10)
```



## Build a workshop 

By default, `build_workshops()` looks for R Markdown source files in a given
path (argument `path`, set to the current working directory by default) and
build the corresponding xaringan presentation(s) (i.e. the HTML slides). For
instance, once I have downloaded the first, I can directly build the English and the French HTML presentations like so: 

```R 
download_workshops(id = 1)
build_workshops()
# or 
build_workshops(path = ".")  # equivalent as this is the default value of path
```

Importantly enough, **`build_workshops()` will download all the packages required for the workshop**. To build only one version of the workshop, `lang` needs to be set to either "en" or "fr".

```R 
# build English version only
build_workshops(lang = "en")
# build French version only
build_workshops(lang = "fr")
```

This function also has several important feature. First, it can build the pdf
version (this required the installation of
[Chromium](https://www.chromium.org/Home) or Google Chrome it not already
installed):

```R 
# this builds both version of the workshop in HTML and pdf 
build_workshops(pdf = TRUE)
```

Second, it can extract the R code from the Markdown source file.

```R 
# build both version of the workshop in HTML and pdf +  extract the R code
build_workshops(pdf = TRUE, script = TRUE)
```

Third, it can update the [CSS template](https://github.com/QCBSRworkshops/templateWorkshops)

```R 
# update CSS template + build both versions in HTML and pdf + extract the code and 
build_workshops(pdf = TRUE, script = TRUE, update_template = TRUE)
```


Finally, it can call `download_workshops()` to download the package:

```R 
# download workshop #1 + update CSS template + build both versions in HTML and pdf + extract the code and update template
build_workshops(id =1, download = TRUE, pdf = TRUE, script = TRUE,  update_template = TRUE)
```

## Presenter email

`mail_workshop()` writes the email to be sent tow weeks before the workshop, for instance: 

```R
# Mail for workshop #7
mail_workshop(7, pres_name = "Kevin Cazelles", lang = "both", 
      details_fr = "à l'UdeM, salle A-2553, campus MIL, le vendredi 28 Février 2020 de 13h à 17h", 
      details_en = "at the UdeM, MIL campus, room A-2553, on Friday February
    28th 2020, 1pm-5pm" 
   ) 
```

will create a HTML version of the email that will pop up in your web browser that you can copy and paste.



## Functions for workshop developers

The main function is obviously `build_workshops()` as it builds the workshop
(see above). That being said, there are other functions worth mentioning. 

First it is often useful to clean up the (e.g., clean the cache), this is possible with `clean_workshops()`, for instance assuming workshop 1 was built in my current working directory, the cache can be cleaned like so: 

```R
clean_workshops(files = FALSE, cache = TRUE)
```

Second, it is possible to update the CSS template without rendering any presentation using `update_template()`. Similarly, it is possible to extract the R code without rendering a presentation using `extract_Rcode_workshop()`.

Third, the first two slides (after the title slide) have now be standardized: it includes various hyperlinks (GitHub repository, wiki, PDF version, R script), and the list of package required (see for instance https://qcbsrworkshops.github.io/workshop01/workshop01-en/workshop01-en.html#2). Those tow slides can be generated using `first_slides()`:

```R 
# the generate the first slides for the workshop 2 and copy the text to the clipboard
first_slides(2, c("dplyr", "tidyr"), clip = TRUE) 
```

Last, the Travis file used for the deployment (see below) can be added with 
`use_travis()`.



## Deployment 

Currently, we are using [Travis CI](https://travis-ci.org/) to check that the package built seamlessly and also to deploy the presentations (English and French in HTML and PDF with the R code). We create all the files needed with the following line (see our Travis file with `use_travis()`):


```yaml
script:
  - Rscript -e "qcbsRworkshops::build_workshops(update_template = TRUE, pdf = TRUE, script = TRUE)"
```

and they are all stored in the folder `public` 

```yaml
before_deploy:
  - mkdir public
  - cp README.md public
  - cp -r workshop* public/
```

which is the one that will be used by Travis that will create a commit and push on the branch `master` of the repository that [GitHub Pages](https://pages.github.com/) turn into a website.

```yaml
deploy:
  provider: pages
  token: $GH_TOKEN
  strategy: git 
  skip_cleanup: true
  keep_history: false
  target_branch: master
  local_dir: public
  on:
    branch: dev
```



## Contributing to the package

The `qcbsRworkshops` R package is released with a [Contributor Code of
Coduct](https://github.com/QCBSRworkshops/qcbsRworkshops/blob/master/CODE_OF_CONDUCT.md). By contributing to this project, you agree to abide by its terms.

Do not hesitate to report issues (could be a feature request, a bug, a typo,
...) and create pull request, but before doing so, first check the [contributing
guidelines](https://github.com/QCBSRworkshops/qcbsRworkshops/blob/master/.github/CONTRIBUTING.md). 